//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop_servis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PCShopFINALEntities : DbContext
    {
        public PCShopFINALEntities()
            : base("name=PCShopFINALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grad> grad { get; set; }
        public virtual DbSet<kategorijeProizvoda> kategorijeProizvoda { get; set; }
        public virtual DbSet<zaposlenici> korisnici { get; set; }
        public virtual DbSet<proizvodjaci> proizvodjaci { get; set; }
        public virtual DbSet<proizvodi> proizvodi { get; set; }
        public virtual DbSet<zaposlenici1> zaposlenici1Set { get; set; }
    
        public virtual ObjectResult<pcshop_pretragaPoNazivu_Result> pcshop_pretragaPoNazivu(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretragaPoNazivu_Result>("pcshop_pretragaPoNazivu", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_CPUCooleri_Result> pcshop_pretraga_CPUCooleri(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_CPUCooleri_Result>("pcshop_pretraga_CPUCooleri", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_GrafickeKartice_Result> pcshop_pretraga_GrafickeKartice(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_GrafickeKartice_Result>("pcshop_pretraga_GrafickeKartice", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_HDDSSD_Result> pcshop_pretraga_HDDSSD(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_HDDSSD_Result>("pcshop_pretraga_HDDSSD", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Kablovi_Result> pcshop_pretraga_Kablovi(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Kablovi_Result>("pcshop_pretraga_Kablovi", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Kucista_Result> pcshop_pretraga_Kucista(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Kucista_Result>("pcshop_pretraga_Kucista", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_MaticnePloce_Result> pcshop_pretraga_MaticnePloce(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_MaticnePloce_Result>("pcshop_pretraga_MaticnePloce", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Mikrofoni_Result> pcshop_pretraga_Mikrofoni(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Mikrofoni_Result>("pcshop_pretraga_Mikrofoni", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Misevi_Result> pcshop_pretraga_Misevi(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Misevi_Result>("pcshop_pretraga_Misevi", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Mobiteli_Result> pcshop_pretraga_Mobiteli(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Mobiteli_Result>("pcshop_pretraga_Mobiteli", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Monitori_Result> pcshop_pretraga_Monitori(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Monitori_Result>("pcshop_pretraga_Monitori", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Napojne_Result> pcshop_pretraga_Napojne(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Napojne_Result>("pcshop_pretraga_Napojne", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Procesori_Result> pcshop_pretraga_Procesori(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Procesori_Result>("pcshop_pretraga_Procesori", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Racunari_Result> pcshop_pretraga_Racunari(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Racunari_Result>("pcshop_pretraga_Racunari", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Slusalice_Result> pcshop_pretraga_Slusalice(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Slusalice_Result>("pcshop_pretraga_Slusalice", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Tastature_Result> pcshop_pretraga_Tastature(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Tastature_Result>("pcshop_pretraga_Tastature", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Televizori_Result> pcshop_pretraga_Televizori(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Televizori_Result>("pcshop_pretraga_Televizori", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Zvucnici_Result> pcshop_pretraga_Zvucnici(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Zvucnici_Result>("pcshop_pretraga_Zvucnici", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretragaRAM_Result> pcshop_pretragaRAM(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretragaRAM_Result>("pcshop_pretragaRAM", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_pretraga_Racunari1_Result> pcshop_pretraga_Racunari1(string naziv)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_pretraga_Racunari1_Result>("pcshop_pretraga_Racunari1", nazivParameter);
        }
    
        public virtual ObjectResult<pcshop_Cmbx_Proizvodjaci_Result> pcshop_Cmbx_Proizvodjaci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_Cmbx_Proizvodjaci_Result>("pcshop_Cmbx_Proizvodjaci");
        }
    
        public virtual int pcshop_proizvodi_Insert(string naziv, string opis, Nullable<decimal> cijena, Nullable<int> kolicina, string sifra, Nullable<int> kategorijaID, Nullable<int> proizvodjacID)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("opis", opis) :
                new ObjectParameter("opis", typeof(string));
    
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("cijena", cijena) :
                new ObjectParameter("cijena", typeof(decimal));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("kolicina", kolicina) :
                new ObjectParameter("kolicina", typeof(int));
    
            var sifraParameter = sifra != null ?
                new ObjectParameter("sifra", sifra) :
                new ObjectParameter("sifra", typeof(string));
    
            var kategorijaIDParameter = kategorijaID.HasValue ?
                new ObjectParameter("kategorijaID", kategorijaID) :
                new ObjectParameter("kategorijaID", typeof(int));
    
            var proizvodjacIDParameter = proizvodjacID.HasValue ?
                new ObjectParameter("proizvodjacID", proizvodjacID) :
                new ObjectParameter("proizvodjacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pcshop_proizvodi_Insert", nazivParameter, opisParameter, cijenaParameter, kolicinaParameter, sifraParameter, kategorijaIDParameter, proizvodjacIDParameter);
        }
    
        public virtual int pcshop_brisanjeProizvoda(Nullable<int> proizvodID)
        {
            var proizvodIDParameter = proizvodID.HasValue ?
                new ObjectParameter("proizvodID", proizvodID) :
                new ObjectParameter("proizvodID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pcshop_brisanjeProizvoda", proizvodIDParameter);
        }
    
        public virtual int pcshop_insertProizvoda(Nullable<int> proizvodiID, string naziv, string opis, Nullable<decimal> cijena, Nullable<int> kolicina, string sifra, Nullable<int> kategorijaID, Nullable<int> proizvodjacID)
        {
            var proizvodiIDParameter = proizvodiID.HasValue ?
                new ObjectParameter("proizvodiID", proizvodiID) :
                new ObjectParameter("proizvodiID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("opis", opis) :
                new ObjectParameter("opis", typeof(string));
    
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("cijena", cijena) :
                new ObjectParameter("cijena", typeof(decimal));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("kolicina", kolicina) :
                new ObjectParameter("kolicina", typeof(int));
    
            var sifraParameter = sifra != null ?
                new ObjectParameter("sifra", sifra) :
                new ObjectParameter("sifra", typeof(string));
    
            var kategorijaIDParameter = kategorijaID.HasValue ?
                new ObjectParameter("kategorijaID", kategorijaID) :
                new ObjectParameter("kategorijaID", typeof(int));
    
            var proizvodjacIDParameter = proizvodjacID.HasValue ?
                new ObjectParameter("proizvodjacID", proizvodjacID) :
                new ObjectParameter("proizvodjacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pcshop_insertProizvoda", proizvodiIDParameter, nazivParameter, opisParameter, cijenaParameter, kolicinaParameter, sifraParameter, kategorijaIDParameter, proizvodjacIDParameter);
        }
    
        public virtual ObjectResult<pcshop_ProizvodiByID_Result> pcshop_ProizvodiByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_ProizvodiByID_Result>("pcshop_ProizvodiByID", idParameter);
        }
    
        public virtual int pcshop_ProizvodiByID1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pcshop_ProizvodiByID1", idParameter);
        }
    
        public virtual int pcshop_updateProizvoda(Nullable<int> proizvodiID, string naziv, string opis, Nullable<decimal> cijena, Nullable<int> kolicina, string sifra, Nullable<int> kategorijaID, Nullable<int> proizvodjacID)
        {
            var proizvodiIDParameter = proizvodiID.HasValue ?
                new ObjectParameter("proizvodiID", proizvodiID) :
                new ObjectParameter("proizvodiID", typeof(int));
    
            var nazivParameter = naziv != null ?
                new ObjectParameter("naziv", naziv) :
                new ObjectParameter("naziv", typeof(string));
    
            var opisParameter = opis != null ?
                new ObjectParameter("opis", opis) :
                new ObjectParameter("opis", typeof(string));
    
            var cijenaParameter = cijena.HasValue ?
                new ObjectParameter("cijena", cijena) :
                new ObjectParameter("cijena", typeof(decimal));
    
            var kolicinaParameter = kolicina.HasValue ?
                new ObjectParameter("kolicina", kolicina) :
                new ObjectParameter("kolicina", typeof(int));
    
            var sifraParameter = sifra != null ?
                new ObjectParameter("sifra", sifra) :
                new ObjectParameter("sifra", typeof(string));
    
            var kategorijaIDParameter = kategorijaID.HasValue ?
                new ObjectParameter("kategorijaID", kategorijaID) :
                new ObjectParameter("kategorijaID", typeof(int));
    
            var proizvodjacIDParameter = proizvodjacID.HasValue ?
                new ObjectParameter("proizvodjacID", proizvodjacID) :
                new ObjectParameter("proizvodjacID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pcshop_updateProizvoda", proizvodiIDParameter, nazivParameter, opisParameter, cijenaParameter, kolicinaParameter, sifraParameter, kategorijaIDParameter, proizvodjacIDParameter);
        }
    
        public virtual ObjectResult<proizvodi> pcshop_ProizvodiByID2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proizvodi>("pcshop_ProizvodiByID2", idParameter);
        }
    
        public virtual ObjectResult<proizvodi> pcshop_ProizvodiByID2(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proizvodi>("pcshop_ProizvodiByID2", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<pcshop_prikaz_CPUCooleri_Result1> pcshop_prikaz_CPUCooleri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_CPUCooleri_Result1>("pcshop_prikaz_CPUCooleri");
        }
    
        public virtual ObjectResult<pcshop_prikaz_GrafickeKartice_Result2> pcshop_prikaz_GrafickeKartice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_GrafickeKartice_Result2>("pcshop_prikaz_GrafickeKartice");
        }
    
        public virtual ObjectResult<pcshop_prikaz_HDDSSD_Result1> pcshop_prikaz_HDDSSD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_HDDSSD_Result1>("pcshop_prikaz_HDDSSD");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Kablovi_Result1> pcshop_prikaz_Kablovi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Kablovi_Result1>("pcshop_prikaz_Kablovi");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Kucista_Result1> pcshop_prikaz_Kucista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Kucista_Result1>("pcshop_prikaz_Kucista");
        }
    
        public virtual ObjectResult<pcshop_prikaz_MaticnePloce_Result1> pcshop_prikaz_MaticnePloce()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_MaticnePloce_Result1>("pcshop_prikaz_MaticnePloce");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Mikrofoni_Result1> pcshop_prikaz_Mikrofoni()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Mikrofoni_Result1>("pcshop_prikaz_Mikrofoni");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Misevi_Result1> pcshop_prikaz_Misevi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Misevi_Result1>("pcshop_prikaz_Misevi");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Mobiteli_Result1> pcshop_prikaz_Mobiteli()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Mobiteli_Result1>("pcshop_prikaz_Mobiteli");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Monitori_Result1> pcshop_prikaz_Monitori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Monitori_Result1>("pcshop_prikaz_Monitori");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Napojne_Result1> pcshop_prikaz_Napojne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Napojne_Result1>("pcshop_prikaz_Napojne");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Procesori_Result1> pcshop_prikaz_Procesori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Procesori_Result1>("pcshop_prikaz_Procesori");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Racunari_Result1> pcshop_prikaz_Racunari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Racunari_Result1>("pcshop_prikaz_Racunari");
        }
    
        public virtual ObjectResult<pcshop_prikaz_RAM_Result1> pcshop_prikaz_RAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_RAM_Result1>("pcshop_prikaz_RAM");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Slusalice_Result1> pcshop_prikaz_Slusalice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Slusalice_Result1>("pcshop_prikaz_Slusalice");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Tastature_Result1> pcshop_prikaz_Tastature()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Tastature_Result1>("pcshop_prikaz_Tastature");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Televizori_Result1> pcshop_prikaz_Televizori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Televizori_Result1>("pcshop_prikaz_Televizori");
        }
    
        public virtual ObjectResult<pcshop_prikaz_Zvucnici_Result1> pcshop_prikaz_Zvucnici()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pcshop_prikaz_Zvucnici_Result1>("pcshop_prikaz_Zvucnici");
        }
    
        public virtual ObjectResult<prijavaZaposlenika_Result> prijavaZaposlenika(string korisnickoIme, string lozinka)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("lozinka", lozinka) :
                new ObjectParameter("lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prijavaZaposlenika_Result>("prijavaZaposlenika", korisnickoImeParameter, lozinkaParameter);
        }
    
        public virtual int zaposleniciDelete(Nullable<int> korisniciID)
        {
            var korisniciIDParameter = korisniciID.HasValue ?
                new ObjectParameter("korisniciID", korisniciID) :
                new ObjectParameter("korisniciID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zaposleniciDelete", korisniciIDParameter);
        }
    
        public virtual int zaposleniciInsert(string ime, string prezime, Nullable<System.DateTime> datumRodjenja, string korisnickoIme, string brojTelefona, string mail, string lozinka, Nullable<int> adresaID)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("ime", ime) :
                new ObjectParameter("ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("prezime", prezime) :
                new ObjectParameter("prezime", typeof(string));
    
            var datumRodjenjaParameter = datumRodjenja.HasValue ?
                new ObjectParameter("datumRodjenja", datumRodjenja) :
                new ObjectParameter("datumRodjenja", typeof(System.DateTime));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var brojTelefonaParameter = brojTelefona != null ?
                new ObjectParameter("brojTelefona", brojTelefona) :
                new ObjectParameter("brojTelefona", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("lozinka", lozinka) :
                new ObjectParameter("lozinka", typeof(string));
    
            var adresaIDParameter = adresaID.HasValue ?
                new ObjectParameter("adresaID", adresaID) :
                new ObjectParameter("adresaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zaposleniciInsert", imeParameter, prezimeParameter, datumRodjenjaParameter, korisnickoImeParameter, brojTelefonaParameter, mailParameter, lozinkaParameter, adresaIDParameter);
        }
    
        public virtual int zaposleniciUpdate(Nullable<int> korisniciID, string ime, string prezime, Nullable<System.DateTime> datumRodjenja, string korisnickoIme, string brojTelefona, string mail, string lozinka, Nullable<int> adresaID)
        {
            var korisniciIDParameter = korisniciID.HasValue ?
                new ObjectParameter("korisniciID", korisniciID) :
                new ObjectParameter("korisniciID", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("ime", ime) :
                new ObjectParameter("ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("prezime", prezime) :
                new ObjectParameter("prezime", typeof(string));
    
            var datumRodjenjaParameter = datumRodjenja.HasValue ?
                new ObjectParameter("datumRodjenja", datumRodjenja) :
                new ObjectParameter("datumRodjenja", typeof(System.DateTime));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var brojTelefonaParameter = brojTelefona != null ?
                new ObjectParameter("brojTelefona", brojTelefona) :
                new ObjectParameter("brojTelefona", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("lozinka", lozinka) :
                new ObjectParameter("lozinka", typeof(string));
    
            var adresaIDParameter = adresaID.HasValue ?
                new ObjectParameter("adresaID", adresaID) :
                new ObjectParameter("adresaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zaposleniciUpdate", korisniciIDParameter, imeParameter, prezimeParameter, datumRodjenjaParameter, korisnickoImeParameter, brojTelefonaParameter, mailParameter, lozinkaParameter, adresaIDParameter);
        }
    
        public virtual ObjectResult<zaposlenici> prijavaZaposlenika1(string korisnickoIme, string lozinka)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("lozinka", lozinka) :
                new ObjectParameter("lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("prijavaZaposlenika1", korisnickoImeParameter, lozinkaParameter);
        }
    
        public virtual ObjectResult<zaposlenici> prijavaZaposlenika1(string korisnickoIme, string lozinka, MergeOption mergeOption)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("korisnickoIme", korisnickoIme) :
                new ObjectParameter("korisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("lozinka", lozinka) :
                new ObjectParameter("lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("prijavaZaposlenika1", mergeOption, korisnickoImeParameter, lozinkaParameter);
        }
    
        public virtual ObjectResult<prikazGradaCmbx_Result> prikazGradaCmbx()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prikazGradaCmbx_Result>("prikazGradaCmbx");
        }
    
        public virtual ObjectResult<prikazZaposlenikaGrid_Result> prikazZaposlenikaGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prikazZaposlenikaGrid_Result>("prikazZaposlenikaGrid");
        }
    
        public virtual ObjectResult<zaposlenici> zaposlenikByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("zaposlenikByID", idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> zaposlenikByID(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("zaposlenikByID", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> zaposlenikByID2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("zaposlenikByID2", idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> zaposlenikByID2(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("zaposlenikByID2", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> ZaposleniciByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("ZaposleniciByID", idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> ZaposleniciByID(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("ZaposleniciByID", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> ZaposleniciByID2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("ZaposleniciByID2", idParameter);
        }
    
        public virtual ObjectResult<zaposlenici> ZaposleniciByID2(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zaposlenici>("ZaposleniciByID2", mergeOption, idParameter);
        }
    }
}
