//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvodi
    {
        public int proizvodiID { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public decimal cijena { get; set; }
        public Nullable<int> kolicina { get; set; }
        public string sifra { get; set; }
        public int kategorijaID { get; set; }
        public int proizvodjacID { get; set; }
    
        public virtual kategorijeProizvoda kategorijeProizvoda { get; set; }
        public virtual proizvodjaci proizvodjaci { get; set; }
    }
}
