//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class proizvodjaci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proizvodjaci()
        {
            this.proizvodi = new HashSet<proizvodi>();
        }
    
        public int proizvodjaciID { get; set; }
        public string naziv { get; set; }
        public string mail { get; set; }
        public string kontaktTel { get; set; }
        public Nullable<int> adresaID { get; set; }
    
        public virtual grad grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proizvodi> proizvodi { get; set; }
    }
}
