//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCShop_servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenici1
    {
        public int korisniciID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<System.DateTime> datumRodjenja { get; set; }
        public string korisnickoIme { get; set; }
        public string brojTelefona { get; set; }
        public string mail { get; set; }
        public string lozinka { get; set; }
        public int adresaID { get; set; }
    
        public virtual grad grad { get; set; }
    }
}
